### PR TITLE
Validate `module-info` provides

### PR DESCRIPTION
**Pull request by SentryMan**
will fail compilation if people forget to add `provides` statements to their module-infos

### CODE REVIEW

**Comment by SentryMan** [comment]
I might have missed some scenarios

**Comment by SentryMan** [comment]
Okay, I think I got most scenarios somebody could do with their module-info. Please review.

**Comment by rob-bygrave** [comment]
Yeah, it probably all works. My gut says that there are not enough separate objects to represent the module info input and validation (so I think we see that via the methods with quite a few args and no unit tests).  

As in the services and foundServices maps could be put into something like "ModuleServicesInfo" and then methods on that to populate it and validate it .. and then unit tests that test just the behaviour of "ModuleServicesInfo".  Then I'd read the unit tests and probably understand it faster.

**Review by rob-bygrave — APPROVED** [review]

**Comment by SentryMan** [comment]
ok, I'll split it into another object

**Pull request merged**
